name: finance
description: The fundamental package for financial computing with Dart.
version: 0.1.0
author: "Ismael Jiménez <ijimenezm@hotmail.es>"
homepage: https://github.com/ismaelJimenez/finance

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.5
  pedantic: ^1.11.0
